### ISSUE TITLE
joblist installer contains hidden files

### ISSUE THREAD

**Issue by psteinb** [holgerbrandl/joblist#51]
I just wanted to install joblist 0.6 and retrieved the installer tarball. it contains hidden files which appear to be OSX specific:

```
$ ls -a joblist_v0.6/
.  ..  jl  ._jl  ._joblist_assembly.jar  joblist_assembly.jar
$ file joblist_v0.6/._*
joblist_v0.6/._jl:                   AppleDouble encoded Macintosh file
joblist_v0.6/._joblist_assembly.jar: AppleDouble encoded Macintosh file
```

are they really needed (as one of them is executable)?

**Comment by holgerbrandl** [comment]
Thanks for the hint. No they are not needed and I've fixed the tar-bundle already
